version: '3.8'

services:
  # Backend proxy server
  api-proxy:
    image: node:20-alpine
    container_name: ai-cost-proxy
    working_dir: /app
    volumes:
      - ./server.js:/app/server.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./.env:/app/.env
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    command: sh -c "npm install && node server.js"
    restart: unless-stopped
    networks:
      - ai-cost-network
    env_file:
      - .env
    environment:
      - NODE_ENV=production

  # Frontend (production build)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-cost-checker
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    restart: unless-stopped
    networks:
      - ai-cost-network
    depends_on:
      - api-proxy
    env_file:
      - .env
    environment:
      - VITE_API_PROXY_URL=http://api-proxy:${PORT:-3001}

networks:
  ai-cost-network:
    driver: bridge
