version: '3.8'

services:
  ai-cost-checker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-cost-checker
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - ai-cost-network

  # Development mode service (optional - comment out when running production)
  ai-cost-checker-dev:
    image: node:20-alpine
    container_name: ai-cost-checker-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    networks:
      - ai-cost-network
    profiles:
      - dev

networks:
  ai-cost-network:
    driver: bridge
